/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExperienceLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'novice' : IDL.Null,
  'expert' : IDL.Null,
});
export const Skill = IDL.Variant({
  'roofing' : IDL.Null,
  'tiling' : IDL.Null,
  'welding' : IDL.Null,
  'plumbing' : IDL.Null,
  'painting' : IDL.Null,
  'electrician' : IDL.Null,
  'generalLabor' : IDL.Null,
  'flooring' : IDL.Null,
  'carpentry' : IDL.Null,
  'masonry' : IDL.Null,
});
export const CertifiedSkill = IDL.Record({
  'skill' : Skill,
  'isCertified' : IDL.Bool,
});
export const SkillWithExperience = IDL.Record({
  'yearsOfExperience' : IDL.Nat,
  'experienceLevel' : ExperienceLevel,
  'skill' : Skill,
  'certificationStatus' : IDL.Vec(CertifiedSkill),
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Time = IDL.Int;
export const JobPosting = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Float64,
  'isCompleted' : IDL.Bool,
  'jobDescription' : IDL.Text,
  'createdAt' : Time,
  'shiftTiming' : IDL.Text,
  'employerId' : IDL.Principal,
  'assignedWorkers' : IDL.Vec(IDL.Text),
  'wageAmount' : IDL.Float64,
  'requiredSkills' : IDL.Vec(SkillWithExperience),
  'location' : Coordinates,
  'workerCount' : IDL.Nat,
});
export const BulkJobResult = IDL.Record({
  'successfullyCreatedJobs' : IDL.Vec(IDL.Text),
  'validJobs' : IDL.Vec(JobPosting),
  'invalidEntries' : IDL.Vec(IDL.Text),
});
export const WageRange = IDL.Record({
  'max' : IDL.Float64,
  'min' : IDL.Float64,
});
export const EmployerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'contactPerson' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'companyName' : IDL.Text,
  'companyType' : IDL.Text,
  'coordinates' : Coordinates,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'completed' : IDL.Null,
  'failed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'mobileMoney' : IDL.Null,
  'cash' : IDL.Null,
  'bankTransfer' : IDL.Null,
  'crypto' : IDL.Null,
});
export const PaymentRecord = IDL.Record({
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'jobId' : IDL.Text,
  'paymentDate' : Time,
  'runningBalance' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const AttendanceRecord = IDL.Record({
  'date' : Time,
  'jobId' : IDL.Text,
  'checkInTime' : IDL.Opt(Time),
  'checkOutTime' : IDL.Opt(Time),
});
export const WorkerProfile = IDL.Record({
  'id' : IDL.Text,
  'completedJobs' : IDL.Nat,
  'reliabilityScore' : IDL.Float64,
  'principal' : IDL.Principal,
  'paymentHistory' : IDL.Vec(PaymentRecord),
  'name' : IDL.Text,
  'wageRange' : WageRange,
  'isAvailable' : IDL.Bool,
  'mobileNumber' : IDL.Text,
  'attendanceRecords' : IDL.Vec(AttendanceRecord),
  'rating' : IDL.Float64,
  'skills' : IDL.Vec(SkillWithExperience),
  'coordinates' : Coordinates,
});
export const UserRole = IDL.Variant({
  'employer' : IDL.Null,
  'worker' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const CandidateMatch = IDL.Record({
  'reliabilityScore' : IDL.Float64,
  'workerId' : IDL.Text,
  'distance' : IDL.Float64,
  'matchScore' : IDL.Float64,
  'skillsMatchPercentage' : IDL.Float64,
});
export const JobReminders = IDL.Record({
  'updateSent' : IDL.Bool,
  'workerId' : IDL.Text,
  'confirmationSent' : IDL.Bool,
  'cancelled' : IDL.Bool,
  'jobId' : IDL.Text,
  'reminderSent' : IDL.Bool,
});
export const JobTemplate = IDL.Record({
  'duration' : IDL.Float64,
  'templateId' : IDL.Text,
  'jobDescription' : IDL.Text,
  'templateName' : IDL.Text,
  'shiftTiming' : IDL.Text,
  'employerId' : IDL.Principal,
  'wageAmount' : IDL.Float64,
  'requiredSkills' : IDL.Vec(SkillWithExperience),
  'location' : Coordinates,
  'workerCount' : IDL.Nat,
});
export const RetentionMetrics = IDL.Record({
  'periodDays' : IDL.Nat,
  'employerRetention' : IDL.Float64,
  'workerRetention' : IDL.Float64,
});
export const RevenueMetrics = IDL.Record({
  'averageRevenuePerJob' : IDL.Float64,
  'totalTransactionVolume' : IDL.Float64,
  'subscriptionTierDistribution' : IDL.Vec(IDL.Text),
});
export const MonthlyFillRate = IDL.Record({
  'month' : IDL.Text,
  'fillRate' : IDL.Float64,
});
export const SystemMetrics = IDL.Record({
  'workerRetentionRate' : IDL.Float64,
  'totalJobsPosted' : IDL.Nat,
  'employerRetentionRate' : IDL.Float64,
  'activeEmployersCount' : IDL.Nat,
  'retentionMetrics' : IDL.Vec(RetentionMetrics),
  'totalWorkersRegistered' : IDL.Nat,
  'jobFillRate' : IDL.Float64,
  'averageTimeToFillJobs' : IDL.Float64,
  'revenueMetrics' : RevenueMetrics,
  'monthlyFillRates' : IDL.Vec(MonthlyFillRate),
});
export const BadgeLevel = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'none' : IDL.Null,
  'silver' : IDL.Null,
});
export const VerifiedWorker = IDL.Record({
  'badgeLevel' : BadgeLevel,
  'completedJobs' : IDL.Nat,
  'reliabilityScore' : IDL.Float64,
  'workerId' : IDL.Text,
  'principal' : IDL.Principal,
  'averageRating' : IDL.Float64,
  'verifiedAt' : Time,
});
export const DayAvailability = IDL.Record({
  'available' : IDL.Bool,
  'timeRange' : IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text)),
});
export const AvailabilityRequest = IDL.Record({
  'available' : IDL.Bool,
  'timeRange' : IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text)),
  'dayIndex' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addFavoriteWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignWorkerToJob' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'bulkJobUpload' : IDL.Func(
      [
        IDL.Vec(
          IDL.Tuple(
            IDL.Text,
            IDL.Vec(SkillWithExperience),
            IDL.Float64,
            IDL.Float64,
            IDL.Text,
            IDL.Nat,
            Coordinates,
            IDL.Text,
          )
        ),
      ],
      [BulkJobResult],
      [],
    ),
  'checkInWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkOutWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createJobPosting' : IDL.Func(
      [
        IDL.Vec(SkillWithExperience),
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        Coordinates,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createWorkerProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(SkillWithExperience),
        WageRange,
        Coordinates,
      ],
      [IDL.Text],
      [],
    ),
  'getAllEmployers' : IDL.Func([], [IDL.Vec(EmployerProfile)], ['query']),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getEmployerFavoriteWorkers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Text)],
      ['query'],
    ),
  'getEmployerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EmployerProfile)],
      ['query'],
    ),
  'getJobMatches' : IDL.Func([IDL.Text], [IDL.Vec(CandidateMatch)], ['query']),
  'getJobPosting' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
  'getJobReminders' : IDL.Func([IDL.Text], [IDL.Vec(JobReminders)], ['query']),
  'getJobTemplates' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(JobTemplate)],
      ['query'],
    ),
  'getMyEmployerProfile' : IDL.Func([], [IDL.Opt(EmployerProfile)], ['query']),
  'getMyJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
  'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVerifiedWorker' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(VerifiedWorker)],
      ['query'],
    ),
  'getWorkerAvailability' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DayAvailability)],
      ['query'],
    ),
  'getWorkerPaymentHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getWorkerProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WorkerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rateWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'recordPayment' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, PaymentMethod],
      [],
      [],
    ),
  'removeFavoriteWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEmployerProfile' : IDL.Func([EmployerProfile], [], []),
  'saveJobTemplate' : IDL.Func([JobTemplate], [], []),
  'updateJobReminders' : IDL.Func([JobReminders], [], []),
  'updateWorkerAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  'updateWorkerAvailabilityWithPattern' : IDL.Func(
      [IDL.Text, IDL.Vec(AvailabilityRequest)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExperienceLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'novice' : IDL.Null,
    'expert' : IDL.Null,
  });
  const Skill = IDL.Variant({
    'roofing' : IDL.Null,
    'tiling' : IDL.Null,
    'welding' : IDL.Null,
    'plumbing' : IDL.Null,
    'painting' : IDL.Null,
    'electrician' : IDL.Null,
    'generalLabor' : IDL.Null,
    'flooring' : IDL.Null,
    'carpentry' : IDL.Null,
    'masonry' : IDL.Null,
  });
  const CertifiedSkill = IDL.Record({
    'skill' : Skill,
    'isCertified' : IDL.Bool,
  });
  const SkillWithExperience = IDL.Record({
    'yearsOfExperience' : IDL.Nat,
    'experienceLevel' : ExperienceLevel,
    'skill' : Skill,
    'certificationStatus' : IDL.Vec(CertifiedSkill),
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Time = IDL.Int;
  const JobPosting = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Float64,
    'isCompleted' : IDL.Bool,
    'jobDescription' : IDL.Text,
    'createdAt' : Time,
    'shiftTiming' : IDL.Text,
    'employerId' : IDL.Principal,
    'assignedWorkers' : IDL.Vec(IDL.Text),
    'wageAmount' : IDL.Float64,
    'requiredSkills' : IDL.Vec(SkillWithExperience),
    'location' : Coordinates,
    'workerCount' : IDL.Nat,
  });
  const BulkJobResult = IDL.Record({
    'successfullyCreatedJobs' : IDL.Vec(IDL.Text),
    'validJobs' : IDL.Vec(JobPosting),
    'invalidEntries' : IDL.Vec(IDL.Text),
  });
  const WageRange = IDL.Record({ 'max' : IDL.Float64, 'min' : IDL.Float64 });
  const EmployerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'contactPerson' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'companyName' : IDL.Text,
    'companyType' : IDL.Text,
    'coordinates' : Coordinates,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'completed' : IDL.Null,
    'failed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'mobileMoney' : IDL.Null,
    'cash' : IDL.Null,
    'bankTransfer' : IDL.Null,
    'crypto' : IDL.Null,
  });
  const PaymentRecord = IDL.Record({
    'paymentStatus' : PaymentStatus,
    'paymentMethod' : PaymentMethod,
    'jobId' : IDL.Text,
    'paymentDate' : Time,
    'runningBalance' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const AttendanceRecord = IDL.Record({
    'date' : Time,
    'jobId' : IDL.Text,
    'checkInTime' : IDL.Opt(Time),
    'checkOutTime' : IDL.Opt(Time),
  });
  const WorkerProfile = IDL.Record({
    'id' : IDL.Text,
    'completedJobs' : IDL.Nat,
    'reliabilityScore' : IDL.Float64,
    'principal' : IDL.Principal,
    'paymentHistory' : IDL.Vec(PaymentRecord),
    'name' : IDL.Text,
    'wageRange' : WageRange,
    'isAvailable' : IDL.Bool,
    'mobileNumber' : IDL.Text,
    'attendanceRecords' : IDL.Vec(AttendanceRecord),
    'rating' : IDL.Float64,
    'skills' : IDL.Vec(SkillWithExperience),
    'coordinates' : Coordinates,
  });
  const UserRole = IDL.Variant({ 'employer' : IDL.Null, 'worker' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const CandidateMatch = IDL.Record({
    'reliabilityScore' : IDL.Float64,
    'workerId' : IDL.Text,
    'distance' : IDL.Float64,
    'matchScore' : IDL.Float64,
    'skillsMatchPercentage' : IDL.Float64,
  });
  const JobReminders = IDL.Record({
    'updateSent' : IDL.Bool,
    'workerId' : IDL.Text,
    'confirmationSent' : IDL.Bool,
    'cancelled' : IDL.Bool,
    'jobId' : IDL.Text,
    'reminderSent' : IDL.Bool,
  });
  const JobTemplate = IDL.Record({
    'duration' : IDL.Float64,
    'templateId' : IDL.Text,
    'jobDescription' : IDL.Text,
    'templateName' : IDL.Text,
    'shiftTiming' : IDL.Text,
    'employerId' : IDL.Principal,
    'wageAmount' : IDL.Float64,
    'requiredSkills' : IDL.Vec(SkillWithExperience),
    'location' : Coordinates,
    'workerCount' : IDL.Nat,
  });
  const RetentionMetrics = IDL.Record({
    'periodDays' : IDL.Nat,
    'employerRetention' : IDL.Float64,
    'workerRetention' : IDL.Float64,
  });
  const RevenueMetrics = IDL.Record({
    'averageRevenuePerJob' : IDL.Float64,
    'totalTransactionVolume' : IDL.Float64,
    'subscriptionTierDistribution' : IDL.Vec(IDL.Text),
  });
  const MonthlyFillRate = IDL.Record({
    'month' : IDL.Text,
    'fillRate' : IDL.Float64,
  });
  const SystemMetrics = IDL.Record({
    'workerRetentionRate' : IDL.Float64,
    'totalJobsPosted' : IDL.Nat,
    'employerRetentionRate' : IDL.Float64,
    'activeEmployersCount' : IDL.Nat,
    'retentionMetrics' : IDL.Vec(RetentionMetrics),
    'totalWorkersRegistered' : IDL.Nat,
    'jobFillRate' : IDL.Float64,
    'averageTimeToFillJobs' : IDL.Float64,
    'revenueMetrics' : RevenueMetrics,
    'monthlyFillRates' : IDL.Vec(MonthlyFillRate),
  });
  const BadgeLevel = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'none' : IDL.Null,
    'silver' : IDL.Null,
  });
  const VerifiedWorker = IDL.Record({
    'badgeLevel' : BadgeLevel,
    'completedJobs' : IDL.Nat,
    'reliabilityScore' : IDL.Float64,
    'workerId' : IDL.Text,
    'principal' : IDL.Principal,
    'averageRating' : IDL.Float64,
    'verifiedAt' : Time,
  });
  const DayAvailability = IDL.Record({
    'available' : IDL.Bool,
    'timeRange' : IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text)),
  });
  const AvailabilityRequest = IDL.Record({
    'available' : IDL.Bool,
    'timeRange' : IDL.Opt(IDL.Tuple(IDL.Text, IDL.Text)),
    'dayIndex' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addFavoriteWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignWorkerToJob' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'bulkJobUpload' : IDL.Func(
        [
          IDL.Vec(
            IDL.Tuple(
              IDL.Text,
              IDL.Vec(SkillWithExperience),
              IDL.Float64,
              IDL.Float64,
              IDL.Text,
              IDL.Nat,
              Coordinates,
              IDL.Text,
            )
          ),
        ],
        [BulkJobResult],
        [],
      ),
    'checkInWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkOutWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createJobPosting' : IDL.Func(
        [
          IDL.Vec(SkillWithExperience),
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          Coordinates,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createWorkerProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(SkillWithExperience),
          WageRange,
          Coordinates,
        ],
        [IDL.Text],
        [],
      ),
    'getAllEmployers' : IDL.Func([], [IDL.Vec(EmployerProfile)], ['query']),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getEmployerFavoriteWorkers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'getEmployerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EmployerProfile)],
        ['query'],
      ),
    'getJobMatches' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CandidateMatch)],
        ['query'],
      ),
    'getJobPosting' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
    'getJobReminders' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(JobReminders)],
        ['query'],
      ),
    'getJobTemplates' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(JobTemplate)],
        ['query'],
      ),
    'getMyEmployerProfile' : IDL.Func(
        [],
        [IDL.Opt(EmployerProfile)],
        ['query'],
      ),
    'getMyJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
    'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVerifiedWorker' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(VerifiedWorker)],
        ['query'],
      ),
    'getWorkerAvailability' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DayAvailability)],
        ['query'],
      ),
    'getWorkerPaymentHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getWorkerProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rateWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'recordPayment' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, PaymentMethod],
        [],
        [],
      ),
    'removeFavoriteWorker' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEmployerProfile' : IDL.Func([EmployerProfile], [], []),
    'saveJobTemplate' : IDL.Func([JobTemplate], [], []),
    'updateJobReminders' : IDL.Func([JobReminders], [], []),
    'updateWorkerAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
    'updateWorkerAvailabilityWithPattern' : IDL.Func(
        [IDL.Text, IDL.Vec(AvailabilityRequest)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };