/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'date' : Time,
  'jobId' : string,
  'checkInTime' : [] | [Time],
  'checkOutTime' : [] | [Time],
}
export interface AvailabilityRequest {
  'available' : boolean,
  'timeRange' : [] | [[string, string]],
  'dayIndex' : bigint,
}
export type BadgeLevel = { 'bronze' : null } |
  { 'gold' : null } |
  { 'none' : null } |
  { 'silver' : null };
export interface BulkJobResult {
  'successfullyCreatedJobs' : Array<string>,
  'validJobs' : Array<JobPosting>,
  'invalidEntries' : Array<string>,
}
export interface CandidateMatch {
  'reliabilityScore' : number,
  'workerId' : string,
  'distance' : number,
  'matchScore' : number,
  'skillsMatchPercentage' : number,
}
export interface CertifiedSkill { 'skill' : Skill, 'isCertified' : boolean }
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface DayAvailability {
  'available' : boolean,
  'timeRange' : [] | [[string, string]],
}
export interface EmployerProfile {
  'principal' : Principal,
  'contactPerson' : string,
  'mobileNumber' : string,
  'companyName' : string,
  'companyType' : string,
  'coordinates' : Coordinates,
}
export type ExperienceLevel = { 'intermediate' : null } |
  { 'novice' : null } |
  { 'expert' : null };
export interface JobPosting {
  'id' : string,
  'duration' : number,
  'isCompleted' : boolean,
  'jobDescription' : string,
  'createdAt' : Time,
  'shiftTiming' : string,
  'employerId' : Principal,
  'assignedWorkers' : Array<string>,
  'wageAmount' : number,
  'requiredSkills' : Array<SkillWithExperience>,
  'location' : Coordinates,
  'workerCount' : bigint,
}
export interface JobReminders {
  'updateSent' : boolean,
  'workerId' : string,
  'confirmationSent' : boolean,
  'cancelled' : boolean,
  'jobId' : string,
  'reminderSent' : boolean,
}
export interface JobTemplate {
  'duration' : number,
  'templateId' : string,
  'jobDescription' : string,
  'templateName' : string,
  'shiftTiming' : string,
  'employerId' : Principal,
  'wageAmount' : number,
  'requiredSkills' : Array<SkillWithExperience>,
  'location' : Coordinates,
  'workerCount' : bigint,
}
export interface MonthlyFillRate { 'month' : string, 'fillRate' : number }
export type PaymentMethod = { 'mobileMoney' : null } |
  { 'cash' : null } |
  { 'bankTransfer' : null } |
  { 'crypto' : null };
export interface PaymentRecord {
  'paymentStatus' : PaymentStatus,
  'paymentMethod' : PaymentMethod,
  'jobId' : string,
  'paymentDate' : Time,
  'runningBalance' : number,
  'amount' : number,
}
export type PaymentStatus = { 'pending' : null } |
  { 'completed' : null } |
  { 'failed' : null };
export interface RetentionMetrics {
  'periodDays' : bigint,
  'employerRetention' : number,
  'workerRetention' : number,
}
export interface RevenueMetrics {
  'averageRevenuePerJob' : number,
  'totalTransactionVolume' : number,
  'subscriptionTierDistribution' : Array<string>,
}
export type Skill = { 'roofing' : null } |
  { 'tiling' : null } |
  { 'welding' : null } |
  { 'plumbing' : null } |
  { 'painting' : null } |
  { 'electrician' : null } |
  { 'generalLabor' : null } |
  { 'flooring' : null } |
  { 'carpentry' : null } |
  { 'masonry' : null };
export interface SkillWithExperience {
  'yearsOfExperience' : bigint,
  'experienceLevel' : ExperienceLevel,
  'skill' : Skill,
  'certificationStatus' : Array<CertifiedSkill>,
}
export interface SystemMetrics {
  'workerRetentionRate' : number,
  'totalJobsPosted' : bigint,
  'employerRetentionRate' : number,
  'activeEmployersCount' : bigint,
  'retentionMetrics' : Array<RetentionMetrics>,
  'totalWorkersRegistered' : bigint,
  'jobFillRate' : number,
  'averageTimeToFillJobs' : number,
  'revenueMetrics' : RevenueMetrics,
  'monthlyFillRates' : Array<MonthlyFillRate>,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'employer' : null } |
  { 'worker' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface VerifiedWorker {
  'badgeLevel' : BadgeLevel,
  'completedJobs' : bigint,
  'reliabilityScore' : number,
  'workerId' : string,
  'principal' : Principal,
  'averageRating' : number,
  'verifiedAt' : Time,
}
export interface WageRange { 'max' : number, 'min' : number }
export interface WorkerProfile {
  'id' : string,
  'completedJobs' : bigint,
  'reliabilityScore' : number,
  'principal' : Principal,
  'paymentHistory' : Array<PaymentRecord>,
  'name' : string,
  'wageRange' : WageRange,
  'isAvailable' : boolean,
  'mobileNumber' : string,
  'attendanceRecords' : Array<AttendanceRecord>,
  'rating' : number,
  'skills' : Array<SkillWithExperience>,
  'coordinates' : Coordinates,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addFavoriteWorker' : ActorMethod<[Principal, string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignWorkerToJob' : ActorMethod<[string, string], undefined>,
  'bulkJobUpload' : ActorMethod<
    [
      Array<
        [
          string,
          Array<SkillWithExperience>,
          number,
          number,
          string,
          bigint,
          Coordinates,
          string,
        ]
      >,
    ],
    BulkJobResult
  >,
  'checkInWorker' : ActorMethod<[string, string], undefined>,
  'checkOutWorker' : ActorMethod<[string, string], undefined>,
  'createJobPosting' : ActorMethod<
    [
      Array<SkillWithExperience>,
      number,
      number,
      string,
      bigint,
      Coordinates,
      string,
    ],
    string
  >,
  'createWorkerProfile' : ActorMethod<
    [string, string, Array<SkillWithExperience>, WageRange, Coordinates],
    string
  >,
  'getAllEmployers' : ActorMethod<[], Array<EmployerProfile>>,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAllWorkers' : ActorMethod<[], Array<WorkerProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getEmployerFavoriteWorkers' : ActorMethod<[Principal], Array<string>>,
  'getEmployerProfile' : ActorMethod<[Principal], [] | [EmployerProfile]>,
  'getJobMatches' : ActorMethod<[string], Array<CandidateMatch>>,
  'getJobPosting' : ActorMethod<[string], [] | [JobPosting]>,
  'getJobReminders' : ActorMethod<[string], Array<JobReminders>>,
  'getJobTemplates' : ActorMethod<[Principal], Array<JobTemplate>>,
  'getMyEmployerProfile' : ActorMethod<[], [] | [EmployerProfile]>,
  'getMyJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getMyWorkerProfile' : ActorMethod<[], [] | [WorkerProfile]>,
  'getSystemMetrics' : ActorMethod<[], SystemMetrics>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getVerifiedWorker' : ActorMethod<[string], [] | [VerifiedWorker]>,
  'getWorkerAvailability' : ActorMethod<[string], Array<DayAvailability>>,
  'getWorkerPaymentHistory' : ActorMethod<[string], Array<PaymentRecord>>,
  'getWorkerProfile' : ActorMethod<[string], [] | [WorkerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rateWorker' : ActorMethod<
    [string, string, bigint, [] | [string]],
    undefined
  >,
  'recordPayment' : ActorMethod<
    [string, string, number, PaymentMethod],
    undefined
  >,
  'removeFavoriteWorker' : ActorMethod<[Principal, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEmployerProfile' : ActorMethod<[EmployerProfile], undefined>,
  'saveJobTemplate' : ActorMethod<[JobTemplate], undefined>,
  'updateJobReminders' : ActorMethod<[JobReminders], undefined>,
  'updateWorkerAvailability' : ActorMethod<[string, boolean], undefined>,
  'updateWorkerAvailabilityWithPattern' : ActorMethod<
    [string, Array<AvailabilityRequest>],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];