/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Skill = IDL.Variant({
  'roofing' : IDL.Null,
  'tiling' : IDL.Null,
  'welding' : IDL.Null,
  'plumbing' : IDL.Null,
  'painting' : IDL.Null,
  'electrician' : IDL.Null,
  'generalLabor' : IDL.Null,
  'flooring' : IDL.Null,
  'carpentry' : IDL.Null,
  'masonry' : IDL.Null,
});
export const Coordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const ExperienceLevel = IDL.Variant({
  'intermediate' : IDL.Null,
  'novice' : IDL.Null,
  'expert' : IDL.Null,
});
export const WageRange = IDL.Record({
  'max' : IDL.Float64,
  'min' : IDL.Float64,
});
export const EmployerProfile = IDL.Record({
  'principal' : IDL.Principal,
  'contactPerson' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'companyName' : IDL.Text,
  'companyType' : IDL.Text,
  'coordinates' : Coordinates,
});
export const Time = IDL.Int;
export const JobPosting = IDL.Record({
  'id' : IDL.Text,
  'duration' : IDL.Float64,
  'isCompleted' : IDL.Bool,
  'jobDescription' : IDL.Text,
  'createdAt' : Time,
  'shiftTiming' : IDL.Text,
  'employerId' : IDL.Principal,
  'assignedWorkers' : IDL.Vec(IDL.Text),
  'wageAmount' : IDL.Float64,
  'requiredSkills' : IDL.Vec(Skill),
  'location' : Coordinates,
  'workerCount' : IDL.Nat,
});
export const PaymentRecord = IDL.Record({
  'jobId' : IDL.Text,
  'isPaid' : IDL.Bool,
  'paymentDate' : Time,
  'amount' : IDL.Float64,
});
export const AttendanceRecord = IDL.Record({
  'date' : Time,
  'jobId' : IDL.Text,
  'checkInTime' : IDL.Opt(Time),
  'checkOutTime' : IDL.Opt(Time),
});
export const WorkerProfile = IDL.Record({
  'id' : IDL.Text,
  'experienceLevel' : ExperienceLevel,
  'completedJobs' : IDL.Nat,
  'reliabilityScore' : IDL.Float64,
  'principal' : IDL.Principal,
  'paymentHistory' : IDL.Vec(PaymentRecord),
  'name' : IDL.Text,
  'wageRange' : WageRange,
  'isAvailable' : IDL.Bool,
  'mobileNumber' : IDL.Text,
  'attendanceRecords' : IDL.Vec(AttendanceRecord),
  'rating' : IDL.Float64,
  'skills' : IDL.Vec(Skill),
  'coordinates' : Coordinates,
});
export const UserRole = IDL.Variant({
  'employer' : IDL.Null,
  'worker' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
export const CandidateMatch = IDL.Record({
  'reliabilityScore' : IDL.Float64,
  'workerId' : IDL.Text,
  'distance' : IDL.Float64,
  'skillsMatchPercentage' : IDL.Float64,
});
export const SystemMetrics = IDL.Record({
  'workerRetentionRate' : IDL.Float64,
  'totalJobsPosted' : IDL.Nat,
  'employerRetentionRate' : IDL.Float64,
  'activeEmployersCount' : IDL.Nat,
  'totalWorkersRegistered' : IDL.Nat,
  'jobFillRate' : IDL.Float64,
  'averageTimeToFillJobs' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'assignWorkerToJob' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkInWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'checkOutWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'createJobPosting' : IDL.Func(
      [
        IDL.Vec(Skill),
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Nat,
        Coordinates,
        IDL.Text,
      ],
      [IDL.Text],
      [],
    ),
  'createWorkerProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Vec(Skill),
        ExperienceLevel,
        WageRange,
        Coordinates,
      ],
      [IDL.Text],
      [],
    ),
  'getAllEmployers' : IDL.Func([], [IDL.Vec(EmployerProfile)], ['query']),
  'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getAllWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getEmployerProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(EmployerProfile)],
      ['query'],
    ),
  'getJobMatches' : IDL.Func([IDL.Text], [IDL.Vec(CandidateMatch)], ['query']),
  'getJobPosting' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
  'getMyEmployerProfile' : IDL.Func([], [IDL.Opt(EmployerProfile)], ['query']),
  'getMyJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
  'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
  'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWorkerPaymentHistory' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(PaymentRecord)],
      ['query'],
    ),
  'getWorkerProfile' : IDL.Func(
      [IDL.Text],
      [IDL.Opt(WorkerProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'rateWorker' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
  'recordPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveEmployerProfile' : IDL.Func([EmployerProfile], [], []),
  'updateWorkerAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Skill = IDL.Variant({
    'roofing' : IDL.Null,
    'tiling' : IDL.Null,
    'welding' : IDL.Null,
    'plumbing' : IDL.Null,
    'painting' : IDL.Null,
    'electrician' : IDL.Null,
    'generalLabor' : IDL.Null,
    'flooring' : IDL.Null,
    'carpentry' : IDL.Null,
    'masonry' : IDL.Null,
  });
  const Coordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const ExperienceLevel = IDL.Variant({
    'intermediate' : IDL.Null,
    'novice' : IDL.Null,
    'expert' : IDL.Null,
  });
  const WageRange = IDL.Record({ 'max' : IDL.Float64, 'min' : IDL.Float64 });
  const EmployerProfile = IDL.Record({
    'principal' : IDL.Principal,
    'contactPerson' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'companyName' : IDL.Text,
    'companyType' : IDL.Text,
    'coordinates' : Coordinates,
  });
  const Time = IDL.Int;
  const JobPosting = IDL.Record({
    'id' : IDL.Text,
    'duration' : IDL.Float64,
    'isCompleted' : IDL.Bool,
    'jobDescription' : IDL.Text,
    'createdAt' : Time,
    'shiftTiming' : IDL.Text,
    'employerId' : IDL.Principal,
    'assignedWorkers' : IDL.Vec(IDL.Text),
    'wageAmount' : IDL.Float64,
    'requiredSkills' : IDL.Vec(Skill),
    'location' : Coordinates,
    'workerCount' : IDL.Nat,
  });
  const PaymentRecord = IDL.Record({
    'jobId' : IDL.Text,
    'isPaid' : IDL.Bool,
    'paymentDate' : Time,
    'amount' : IDL.Float64,
  });
  const AttendanceRecord = IDL.Record({
    'date' : Time,
    'jobId' : IDL.Text,
    'checkInTime' : IDL.Opt(Time),
    'checkOutTime' : IDL.Opt(Time),
  });
  const WorkerProfile = IDL.Record({
    'id' : IDL.Text,
    'experienceLevel' : ExperienceLevel,
    'completedJobs' : IDL.Nat,
    'reliabilityScore' : IDL.Float64,
    'principal' : IDL.Principal,
    'paymentHistory' : IDL.Vec(PaymentRecord),
    'name' : IDL.Text,
    'wageRange' : WageRange,
    'isAvailable' : IDL.Bool,
    'mobileNumber' : IDL.Text,
    'attendanceRecords' : IDL.Vec(AttendanceRecord),
    'rating' : IDL.Float64,
    'skills' : IDL.Vec(Skill),
    'coordinates' : Coordinates,
  });
  const UserRole = IDL.Variant({ 'employer' : IDL.Null, 'worker' : IDL.Null });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : UserRole });
  const CandidateMatch = IDL.Record({
    'reliabilityScore' : IDL.Float64,
    'workerId' : IDL.Text,
    'distance' : IDL.Float64,
    'skillsMatchPercentage' : IDL.Float64,
  });
  const SystemMetrics = IDL.Record({
    'workerRetentionRate' : IDL.Float64,
    'totalJobsPosted' : IDL.Nat,
    'employerRetentionRate' : IDL.Float64,
    'activeEmployersCount' : IDL.Nat,
    'totalWorkersRegistered' : IDL.Nat,
    'jobFillRate' : IDL.Float64,
    'averageTimeToFillJobs' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'assignWorkerToJob' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkInWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'checkOutWorker' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'createJobPosting' : IDL.Func(
        [
          IDL.Vec(Skill),
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Nat,
          Coordinates,
          IDL.Text,
        ],
        [IDL.Text],
        [],
      ),
    'createWorkerProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Vec(Skill),
          ExperienceLevel,
          WageRange,
          Coordinates,
        ],
        [IDL.Text],
        [],
      ),
    'getAllEmployers' : IDL.Func([], [IDL.Vec(EmployerProfile)], ['query']),
    'getAllJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getAllWorkers' : IDL.Func([], [IDL.Vec(WorkerProfile)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getEmployerProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(EmployerProfile)],
        ['query'],
      ),
    'getJobMatches' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(CandidateMatch)],
        ['query'],
      ),
    'getJobPosting' : IDL.Func([IDL.Text], [IDL.Opt(JobPosting)], ['query']),
    'getMyEmployerProfile' : IDL.Func(
        [],
        [IDL.Opt(EmployerProfile)],
        ['query'],
      ),
    'getMyJobPostings' : IDL.Func([], [IDL.Vec(JobPosting)], ['query']),
    'getMyWorkerProfile' : IDL.Func([], [IDL.Opt(WorkerProfile)], ['query']),
    'getSystemMetrics' : IDL.Func([], [SystemMetrics], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWorkerPaymentHistory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(PaymentRecord)],
        ['query'],
      ),
    'getWorkerProfile' : IDL.Func(
        [IDL.Text],
        [IDL.Opt(WorkerProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'rateWorker' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
    'recordPayment' : IDL.Func([IDL.Text, IDL.Text, IDL.Float64], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveEmployerProfile' : IDL.Func([EmployerProfile], [], []),
    'updateWorkerAvailability' : IDL.Func([IDL.Text, IDL.Bool], [], []),
  });
};

export const init = ({ IDL }) => { return []; };