/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AttendanceRecord {
  'date' : Time,
  'jobId' : string,
  'checkInTime' : [] | [Time],
  'checkOutTime' : [] | [Time],
}
export interface CandidateMatch {
  'reliabilityScore' : number,
  'workerId' : string,
  'distance' : number,
  'skillsMatchPercentage' : number,
}
export interface Coordinates { 'latitude' : number, 'longitude' : number }
export interface EmployerProfile {
  'principal' : Principal,
  'contactPerson' : string,
  'mobileNumber' : string,
  'companyName' : string,
  'companyType' : string,
  'coordinates' : Coordinates,
}
export type ExperienceLevel = { 'intermediate' : null } |
  { 'novice' : null } |
  { 'expert' : null };
export interface JobPosting {
  'id' : string,
  'duration' : number,
  'isCompleted' : boolean,
  'jobDescription' : string,
  'createdAt' : Time,
  'shiftTiming' : string,
  'employerId' : Principal,
  'assignedWorkers' : Array<string>,
  'wageAmount' : number,
  'requiredSkills' : Array<Skill>,
  'location' : Coordinates,
  'workerCount' : bigint,
}
export interface PaymentRecord {
  'jobId' : string,
  'isPaid' : boolean,
  'paymentDate' : Time,
  'amount' : number,
}
export type Skill = { 'roofing' : null } |
  { 'tiling' : null } |
  { 'welding' : null } |
  { 'plumbing' : null } |
  { 'painting' : null } |
  { 'electrician' : null } |
  { 'generalLabor' : null } |
  { 'flooring' : null } |
  { 'carpentry' : null } |
  { 'masonry' : null };
export interface SystemMetrics {
  'workerRetentionRate' : number,
  'totalJobsPosted' : bigint,
  'employerRetentionRate' : number,
  'activeEmployersCount' : bigint,
  'totalWorkersRegistered' : bigint,
  'jobFillRate' : number,
  'averageTimeToFillJobs' : number,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'role' : UserRole }
export type UserRole = { 'employer' : null } |
  { 'worker' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WageRange { 'max' : number, 'min' : number }
export interface WorkerProfile {
  'id' : string,
  'experienceLevel' : ExperienceLevel,
  'completedJobs' : bigint,
  'reliabilityScore' : number,
  'principal' : Principal,
  'paymentHistory' : Array<PaymentRecord>,
  'name' : string,
  'wageRange' : WageRange,
  'isAvailable' : boolean,
  'mobileNumber' : string,
  'attendanceRecords' : Array<AttendanceRecord>,
  'rating' : number,
  'skills' : Array<Skill>,
  'coordinates' : Coordinates,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'assignWorkerToJob' : ActorMethod<[string, string], undefined>,
  'checkInWorker' : ActorMethod<[string, string], undefined>,
  'checkOutWorker' : ActorMethod<[string, string], undefined>,
  'createJobPosting' : ActorMethod<
    [Array<Skill>, number, number, string, bigint, Coordinates, string],
    string
  >,
  'createWorkerProfile' : ActorMethod<
    [string, string, Array<Skill>, ExperienceLevel, WageRange, Coordinates],
    string
  >,
  'getAllEmployers' : ActorMethod<[], Array<EmployerProfile>>,
  'getAllJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getAllWorkers' : ActorMethod<[], Array<WorkerProfile>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getEmployerProfile' : ActorMethod<[Principal], [] | [EmployerProfile]>,
  'getJobMatches' : ActorMethod<[string], Array<CandidateMatch>>,
  'getJobPosting' : ActorMethod<[string], [] | [JobPosting]>,
  'getMyEmployerProfile' : ActorMethod<[], [] | [EmployerProfile]>,
  'getMyJobPostings' : ActorMethod<[], Array<JobPosting>>,
  'getMyWorkerProfile' : ActorMethod<[], [] | [WorkerProfile]>,
  'getSystemMetrics' : ActorMethod<[], SystemMetrics>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWorkerPaymentHistory' : ActorMethod<[string], Array<PaymentRecord>>,
  'getWorkerProfile' : ActorMethod<[string], [] | [WorkerProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'rateWorker' : ActorMethod<
    [string, string, bigint, [] | [string]],
    undefined
  >,
  'recordPayment' : ActorMethod<[string, string, number], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveEmployerProfile' : ActorMethod<[EmployerProfile], undefined>,
  'updateWorkerAvailability' : ActorMethod<[string, boolean], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];