/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SystemMetrics {
    workerRetentionRate: number;
    totalJobsPosted: bigint;
    employerRetentionRate: number;
    activeEmployersCount: bigint;
    totalWorkersRegistered: bigint;
    jobFillRate: number;
    averageTimeToFillJobs: number;
}
export type Time = bigint;
export interface Coordinates {
    latitude: number;
    longitude: number;
}
export interface PaymentRecord {
    jobId: string;
    isPaid: boolean;
    paymentDate: Time;
    amount: number;
}
export interface JobPosting {
    id: string;
    duration: number;
    isCompleted: boolean;
    jobDescription: string;
    createdAt: Time;
    shiftTiming: string;
    employerId: Principal;
    assignedWorkers: Array<string>;
    wageAmount: number;
    requiredSkills: Array<Skill>;
    location: Coordinates;
    workerCount: bigint;
}
export interface CandidateMatch {
    reliabilityScore: number;
    workerId: string;
    distance: number;
    skillsMatchPercentage: number;
}
export interface WorkerProfile {
    id: string;
    experienceLevel: ExperienceLevel;
    completedJobs: bigint;
    reliabilityScore: number;
    principal: Principal;
    paymentHistory: Array<PaymentRecord>;
    name: string;
    wageRange: WageRange;
    isAvailable: boolean;
    mobileNumber: string;
    attendanceRecords: Array<AttendanceRecord>;
    rating: number;
    skills: Array<Skill>;
    coordinates: Coordinates;
}
export interface AttendanceRecord {
    date: Time;
    jobId: string;
    checkInTime?: Time;
    checkOutTime?: Time;
}
export interface EmployerProfile {
    principal: Principal;
    contactPerson: string;
    mobileNumber: string;
    companyName: string;
    companyType: string;
    coordinates: Coordinates;
}
export interface UserProfile {
    name: string;
    role: UserRole;
}
export interface WageRange {
    max: number;
    min: number;
}
export enum ExperienceLevel {
    intermediate = "intermediate",
    novice = "novice",
    expert = "expert"
}
export enum Skill {
    roofing = "roofing",
    tiling = "tiling",
    welding = "welding",
    plumbing = "plumbing",
    painting = "painting",
    electrician = "electrician",
    generalLabor = "generalLabor",
    flooring = "flooring",
    carpentry = "carpentry",
    masonry = "masonry"
}
export enum UserRole {
    employer = "employer",
    worker = "worker"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    assignWorkerToJob(jobId: string, workerId: string): Promise<void>;
    checkInWorker(jobId: string, workerId: string): Promise<void>;
    checkOutWorker(jobId: string, workerId: string): Promise<void>;
    createJobPosting(requiredSkills: Array<Skill>, wageAmount: number, duration: number, shiftTiming: string, workerCount: bigint, location: Coordinates, jobDescription: string): Promise<string>;
    createWorkerProfile(name: string, mobileNumber: string, skills: Array<Skill>, experienceLevel: ExperienceLevel, wageRange: WageRange, coordinates: Coordinates): Promise<string>;
    getAllEmployers(): Promise<Array<EmployerProfile>>;
    getAllJobPostings(): Promise<Array<JobPosting>>;
    getAllWorkers(): Promise<Array<WorkerProfile>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getEmployerProfile(employer: Principal): Promise<EmployerProfile | null>;
    getJobMatches(jobId: string): Promise<Array<CandidateMatch>>;
    getJobPosting(jobId: string): Promise<JobPosting | null>;
    getMyEmployerProfile(): Promise<EmployerProfile | null>;
    getMyJobPostings(): Promise<Array<JobPosting>>;
    getMyWorkerProfile(): Promise<WorkerProfile | null>;
    getSystemMetrics(): Promise<SystemMetrics>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    getWorkerPaymentHistory(workerId: string): Promise<Array<PaymentRecord>>;
    getWorkerProfile(workerId: string): Promise<WorkerProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    rateWorker(jobId: string, workerId: string, rating: bigint, remarks: string | null): Promise<void>;
    recordPayment(workerId: string, jobId: string, amount: number): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveEmployerProfile(profile: EmployerProfile): Promise<void>;
    updateWorkerAvailability(workerId: string, isAvailable: boolean): Promise<void>;
}
import type { AttendanceRecord as _AttendanceRecord, Coordinates as _Coordinates, EmployerProfile as _EmployerProfile, ExperienceLevel as _ExperienceLevel, JobPosting as _JobPosting, PaymentRecord as _PaymentRecord, Skill as _Skill, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1, WageRange as _WageRange, WorkerProfile as _WorkerProfile } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignWorkerToJob(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignWorkerToJob(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignWorkerToJob(arg0, arg1);
            return result;
        }
    }
    async checkInWorker(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkInWorker(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkInWorker(arg0, arg1);
            return result;
        }
    }
    async checkOutWorker(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.checkOutWorker(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.checkOutWorker(arg0, arg1);
            return result;
        }
    }
    async createJobPosting(arg0: Array<Skill>, arg1: number, arg2: number, arg3: string, arg4: bigint, arg5: Coordinates, arg6: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createJobPosting(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createJobPosting(to_candid_vec_n3(this._uploadFile, this._downloadFile, arg0), arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async createWorkerProfile(arg0: string, arg1: string, arg2: Array<Skill>, arg3: ExperienceLevel, arg4: WageRange, arg5: Coordinates): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkerProfile(arg0, arg1, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg2), to_candid_ExperienceLevel_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkerProfile(arg0, arg1, to_candid_vec_n3(this._uploadFile, this._downloadFile, arg2), to_candid_ExperienceLevel_n6(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return result;
        }
    }
    async getAllEmployers(): Promise<Array<EmployerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllEmployers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllEmployers();
            return result;
        }
    }
    async getAllJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllJobPostings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllJobPostings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkers(): Promise<Array<WorkerProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkers();
                return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkers();
            return from_candid_vec_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getEmployerProfile(arg0: Principal): Promise<EmployerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getEmployerProfile(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getEmployerProfile(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobMatches(arg0: string): Promise<Array<CandidateMatch>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobMatches(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobMatches(arg0);
            return result;
        }
    }
    async getJobPosting(arg0: string): Promise<JobPosting | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobPosting(arg0);
                return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobPosting(arg0);
            return from_candid_opt_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyEmployerProfile(): Promise<EmployerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyEmployerProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyEmployerProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyJobPostings(): Promise<Array<JobPosting>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyJobPostings();
                return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyJobPostings();
            return from_candid_vec_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkerProfile(): Promise<WorkerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkerProfile();
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkerProfile();
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSystemMetrics(): Promise<SystemMetrics> {
        if (this.processError) {
            try {
                const result = await this.actor.getSystemMetrics();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSystemMetrics();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkerPaymentHistory(arg0: string): Promise<Array<PaymentRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerPaymentHistory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerPaymentHistory(arg0);
            return result;
        }
    }
    async getWorkerProfile(arg0: string): Promise<WorkerProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkerProfile(arg0);
                return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkerProfile(arg0);
            return from_candid_opt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async rateWorker(arg0: string, arg1: string, arg2: bigint, arg3: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rateWorker(arg0, arg1, arg2, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rateWorker(arg0, arg1, arg2, to_candid_opt_n33(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async recordPayment(arg0: string, arg1: string, arg2: number): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordPayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordPayment(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async saveEmployerProfile(arg0: EmployerProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveEmployerProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveEmployerProfile(arg0);
            return result;
        }
    }
    async updateWorkerAvailability(arg0: string, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkerAvailability(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkerAvailability(arg0, arg1);
            return result;
        }
    }
}
function from_candid_AttendanceRecord_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AttendanceRecord): AttendanceRecord {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_ExperienceLevel_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExperienceLevel): ExperienceLevel {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_JobPosting_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _JobPosting): JobPosting {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Skill_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Skill): Skill {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerProfile_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerProfile): WorkerProfile {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_EmployerProfile]): EmployerProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobPosting]): JobPosting | null {
    return value.length === 0 ? null : from_candid_JobPosting_n9(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_WorkerProfile]): WorkerProfile | null {
    return value.length === 0 ? null : from_candid_WorkerProfile_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    duration: number;
    isCompleted: boolean;
    jobDescription: string;
    createdAt: _Time;
    shiftTiming: string;
    employerId: Principal;
    assignedWorkers: Array<string>;
    wageAmount: number;
    requiredSkills: Array<_Skill>;
    location: _Coordinates;
    workerCount: bigint;
}): {
    id: string;
    duration: number;
    isCompleted: boolean;
    jobDescription: string;
    createdAt: Time;
    shiftTiming: string;
    employerId: Principal;
    assignedWorkers: Array<string>;
    wageAmount: number;
    requiredSkills: Array<Skill>;
    location: Coordinates;
    workerCount: bigint;
} {
    return {
        id: value.id,
        duration: value.duration,
        isCompleted: value.isCompleted,
        jobDescription: value.jobDescription,
        createdAt: value.createdAt,
        shiftTiming: value.shiftTiming,
        employerId: value.employerId,
        assignedWorkers: value.assignedWorkers,
        wageAmount: value.wageAmount,
        requiredSkills: from_candid_vec_n11(_uploadFile, _downloadFile, value.requiredSkills),
        location: value.location,
        workerCount: value.workerCount
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    experienceLevel: _ExperienceLevel;
    completedJobs: bigint;
    reliabilityScore: number;
    principal: Principal;
    paymentHistory: Array<_PaymentRecord>;
    name: string;
    wageRange: _WageRange;
    isAvailable: boolean;
    mobileNumber: string;
    attendanceRecords: Array<_AttendanceRecord>;
    rating: number;
    skills: Array<_Skill>;
    coordinates: _Coordinates;
}): {
    id: string;
    experienceLevel: ExperienceLevel;
    completedJobs: bigint;
    reliabilityScore: number;
    principal: Principal;
    paymentHistory: Array<PaymentRecord>;
    name: string;
    wageRange: WageRange;
    isAvailable: boolean;
    mobileNumber: string;
    attendanceRecords: Array<AttendanceRecord>;
    rating: number;
    skills: Array<Skill>;
    coordinates: Coordinates;
} {
    return {
        id: value.id,
        experienceLevel: from_candid_ExperienceLevel_n17(_uploadFile, _downloadFile, value.experienceLevel),
        completedJobs: value.completedJobs,
        reliabilityScore: value.reliabilityScore,
        principal: value.principal,
        paymentHistory: value.paymentHistory,
        name: value.name,
        wageRange: value.wageRange,
        isAvailable: value.isAvailable,
        mobileNumber: value.mobileNumber,
        attendanceRecords: from_candid_vec_n19(_uploadFile, _downloadFile, value.attendanceRecords),
        rating: value.rating,
        skills: from_candid_vec_n11(_uploadFile, _downloadFile, value.skills),
        coordinates: value.coordinates
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    date: _Time;
    jobId: string;
    checkInTime: [] | [_Time];
    checkOutTime: [] | [_Time];
}): {
    date: Time;
    jobId: string;
    checkInTime?: Time;
    checkOutTime?: Time;
} {
    return {
        date: value.date,
        jobId: value.jobId,
        checkInTime: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.checkInTime)),
        checkOutTime: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.checkOutTime))
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: _UserRole;
}): {
    name: string;
    role: UserRole;
} {
    return {
        name: value.name,
        role: from_candid_UserRole_n26(_uploadFile, _downloadFile, value.role)
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    roofing: null;
} | {
    tiling: null;
} | {
    welding: null;
} | {
    plumbing: null;
} | {
    painting: null;
} | {
    electrician: null;
} | {
    generalLabor: null;
} | {
    flooring: null;
} | {
    carpentry: null;
} | {
    masonry: null;
}): Skill {
    return "roofing" in value ? Skill.roofing : "tiling" in value ? Skill.tiling : "welding" in value ? Skill.welding : "plumbing" in value ? Skill.plumbing : "painting" in value ? Skill.painting : "electrician" in value ? Skill.electrician : "generalLabor" in value ? Skill.generalLabor : "flooring" in value ? Skill.flooring : "carpentry" in value ? Skill.carpentry : "masonry" in value ? Skill.masonry : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    intermediate: null;
} | {
    novice: null;
} | {
    expert: null;
}): ExperienceLevel {
    return "intermediate" in value ? ExperienceLevel.intermediate : "novice" in value ? ExperienceLevel.novice : "expert" in value ? ExperienceLevel.expert : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    employer: null;
} | {
    worker: null;
}): UserRole {
    return "employer" in value ? UserRole.employer : "worker" in value ? UserRole.worker : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Skill>): Array<Skill> {
    return value.map((x)=>from_candid_Skill_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkerProfile>): Array<WorkerProfile> {
    return value.map((x)=>from_candid_WorkerProfile_n15(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AttendanceRecord>): Array<AttendanceRecord> {
    return value.map((x)=>from_candid_AttendanceRecord_n20(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_JobPosting>): Array<JobPosting> {
    return value.map((x)=>from_candid_JobPosting_n9(_uploadFile, _downloadFile, x));
}
function to_candid_ExperienceLevel_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): _ExperienceLevel {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_Skill_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Skill): _Skill {
    return to_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n37(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    role: UserRole;
}): {
    name: string;
    role: _UserRole;
} {
    return {
        name: value.name,
        role: to_candid_UserRole_n36(_uploadFile, _downloadFile, value.role)
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    employer: null;
} | {
    worker: null;
} {
    return value == UserRole.employer ? {
        employer: null
    } : value == UserRole.worker ? {
        worker: null
    } : value;
}
function to_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Skill): {
    roofing: null;
} | {
    tiling: null;
} | {
    welding: null;
} | {
    plumbing: null;
} | {
    painting: null;
} | {
    electrician: null;
} | {
    generalLabor: null;
} | {
    flooring: null;
} | {
    carpentry: null;
} | {
    masonry: null;
} {
    return value == Skill.roofing ? {
        roofing: null
    } : value == Skill.tiling ? {
        tiling: null
    } : value == Skill.welding ? {
        welding: null
    } : value == Skill.plumbing ? {
        plumbing: null
    } : value == Skill.painting ? {
        painting: null
    } : value == Skill.electrician ? {
        electrician: null
    } : value == Skill.generalLabor ? {
        generalLabor: null
    } : value == Skill.flooring ? {
        flooring: null
    } : value == Skill.carpentry ? {
        carpentry: null
    } : value == Skill.masonry ? {
        masonry: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExperienceLevel): {
    intermediate: null;
} | {
    novice: null;
} | {
    expert: null;
} {
    return value == ExperienceLevel.intermediate ? {
        intermediate: null
    } : value == ExperienceLevel.novice ? {
        novice: null
    } : value == ExperienceLevel.expert ? {
        expert: null
    } : value;
}
function to_candid_vec_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Skill>): Array<_Skill> {
    return value.map((x)=>to_candid_Skill_n4(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
